# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "DockerHub Container Registry"
              repository: "tashikmoin/cicd"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: |
                $(tag)

  - stage: Provision
    displayName: "... Provisioning on Azure using Terraform ..."
    dependsOn: Build
    jobs:
      - job: Provision
        displayName: "Provisioning Container Instance"
        pool:
          vmImage: "ubuntu-latest" # An image for a temporary server where scripts will run.
        variables:
          - group: TerraformVariables # Name of library on AzureDevOps where environmental variables are stored
        steps:
          # The input false and auto approve flag eliminates the interaction with the cli.
          - script: |
              set -e
              terraform init -input=false -backend-config=backend.conf
              terraform apply -input=false -auto-approve
            name: "RunTerraform"
            displayName: "Run Terraform"
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              TF_VAR_imagetag: $(tag)
